# serverless.yml

service: ios-apns-function

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  ios-apns-function:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'